### PR TITLE
Fixes deprecated numpy.float; adds numpy.double.

### LINKED ISSUE #23: bioverse/constants.py uses deprecated alias `np.float`
on numpy >= 1.20, an AttributeError occurs when the `constants` submodule is imported.

```
Traceback (most recent call last):
  File "/Users/schlecker/repos/magmaocean/src/scripts/radiusevolution.py", line 6, in <module>
    from bioverse.constants import CONST
  File "/Users/schlecker/repos/magmaocean/.snakemake/conda/fdb820a9d52d4edc3a3d4beeccf13c28/lib/python3.9/site-packages/bioverse/constants.py", line 42, in <module>
    FLOAT_TYPES = (float,np.float,np.float_,np.float64)
  File "/Users/schlecker/repos/magmaocean/.snakemake/conda/fdb820a9d52d4edc3a3d4beeccf13c28/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### PR DESCRIPTION
**Pull request by Ahmed-Z-D**
This pull request fixes #23  by removing the deprecated `numpy.float` alias from `constants.py` Additionally, I have included a new alias `numpy.double` as a replacement, which represents the 64-bit floating-point data type and is equivalent to `numpy.float64`.

With these changes, the code will be updated to use[ the recommended aliases](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) for the appropriate data type, and the deprecated alias will be removed.

### CODE REVIEW

**Comment by matiscke** [comment]
@Ahmed-Z-D we are very sorry for the long delay. Feel free to re-open this PR, which indeed would be a fix of the issue. Thanks so much for contributing!

**Comment by Ahmed-Z-D** [comment]
@matiscke, thank you for your suggestion to reopen this pull request. Following your suggestion, this PR has been reopened.

**Comment by matiscke** [comment]
There were some other incompatibilities among pandas, astropy, and numpy >= 1.20.
The additional commits should fix those.

**Review by matiscke — APPROVED** [review]

**Comment by matiscke** [comment]
Thanks a lot, @Ahmed-Z-D!

**Pull request merged**
